services:
  postgresql:
    image: postgres:14
    platform: linux/amd64
    container_name: postgresql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "l??pT-87pBqE2hN9-zY/)"
      POSTGRES_DB: "prism"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./prism-postgres_init:/docker-entrypoint-initdb.d
    networks:
      - prismnetwork

  prism-server:
    build:
      context: ./prism-server
      args:
        POSTGRES_PWD: "l??pT-87pBqE2hN9-zY/)"
    platform: linux/amd64
    container_name: prism-server
    # runtime: nvidia # Requires NVIDIA Container Toolkit on the host for GPU access
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      POSTGRES_PWD: "l??pT-87pBqE2hN9-zY/)"
      POLYGON_API_KEY: ${POLYGON_API_KEY}
    volumes:
      - ./prism-server_data:/workspace/data
      - ./prism-server:/workspace/src
      - ./prism-evaluation:/workspace/eval
    ports:
      - "8082:8082"
    networks:
      - prismnetwork
    stdin_open: true # Keeps STDIN open (like -i)
    tty: true # Allocates a TTY (like -t)

  prism-website:
    build: ./prism-website
    platform: linux/amd64
    container_name: prism-website
    volumes:
      - ./prism-website:/usr/src/app
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    networks:
      - prismnetwork
    stdin_open: true # Keeps STDIN open (like -i)
    tty: true # Allocates a TTY (like -t)
    restart: unless-stopped

volumes:
  pgdata:

networks:
  prismnetwork:
    driver: bridge
