services:
  web:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prism-website
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
        - .:/usr/src/app
    restart: unless-stopped
